# Generated by Django 2.0.6 on 2019-02-21 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('pageNumber', models.IntegerField()),
                ('gender', models.CharField(max_length=300)),
                ('publishedDate', models.DateTimeField(default=datetime.datetime(2019, 2, 21, 17, 38, 59, 279723, tzinfo=utc))),
            ],
        ),
    ]
