# Generated by Django 2.0.6 on 2019-02-21 18:55

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('yearAttirbutes', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 18, 55, 7, 305389, tzinfo=utc)),
        ),
    ]
